<?php
/**
 * @file
 * Contains \Drupal\feedbacksform\Form
 */

namespace Drupal\feedbacksform\Form;

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\PropertyAccess\PropertyAccess;

/**
 * Form with modal window.
 */
class AjaxFormSubmit extends FormBase {

  /**
   * {@inheritdoc}.
   */
  public function getFormId() {
    return 'ajax_form_submit';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['system_messages'] = [
      '#markup' => '<div id="form-system-messages"></div>',
      '#weight' => -100,
    ];
    $form['first_name'] = [
      '#type' => 'textfield',
      '#title' => $this->t('First name'),
      '#desctiption' => $this->t('Enter your First name.'),
      '#required' => TRUE,
      '#ajax' => [
        'callback' => '::validateFirstNameAjax',
        'event' => 'change',
      ],
      '#suffix' => '<div class="first-name-validation-message"></div>',
    ];
    $form['email_address'] = [
      '#type' => 'email',
      '#title' => $this->t('E-mail'),
      '#description' => $this->t('Please enter your e-mail address'),
      '#required' => TRUE,
    ];
    $form['phone_number'] = [
      '#type' => 'tel',
      '#title' => $this->t('Phone number'),
      '#description' => $this->t('Please, enter your phone number'),
      '#required' => TRUE,
      '#maxlength' => '10',
    ];
    $form['feedback'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Feedback'),
      '#description' => $this->t('Please, enter your feedback'),
      '#required' => TRUE,
    ];
    $form['profile_image'] = [
      '#type' => 'managed_file',
      '#title' => t('Avatar picture (maximum upload size 2MB)'),
      '#upload_validators' => array(
        'file_validate_extensions' => array('png jpg jpeg'),
        'file_validate_size' => array(2097152),
      ),
      '#upload_location' => 'public://avatar-pictures'
    ];
    $form['feedback_image'] = [
      '#type' => 'managed_file',
      '#title' => t('Feedback picture (maximum upload size 5MB)'),
      '#upload_validators' => array(
        'file_validate_extensions' => array('png jpg jpeg'),
        'file_validate_size' => array(3145728),
      ),
      '#upload_location' => 'public://feedback-pictures'
    ];
    $form['submit'] = [
      '#type' => 'submit',
      '#name' => 'submit',
      '#value' => 'Submit this form',
    ];
    $form['#cache']['max-age'] = 0;
    return $form;
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    if (strlen ($form_state -> getValue('first_name')) <= '2' || (strlen($form_state->getValue('first_name')) >='100')) {
      $form_state->setErrorByName('first_name', 'The valid firstname should contain between 2 and 100 characters');
    }
    if (strlen ($form_state->getValue('phone_number')) <10 || !is_numeric($form_state->getValue('phone_number'))){
      $form_state->setErrorByName('phone_number', 'Correct Ukrainian phone number must be in format 0-xxx-xxx-xxx');
    }
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    \Drupal::messenger()->addMessage('Thank you for feedback!');
  }
}
